imu:
  gyro_bias: null
joints:
  motor_zero_rad:
  - 2.2398
  - 4.9869
  - 8.253
  - 1.9309
  - -10.2711
  - 10.1172
  - -2.6871
  - -16.61
  - -6.6306
  - -0.1506
  sign:
  - -1.0
  - 1.0
  - -1.0
  - 1.0
  - -1.0
  - 1.0
  - -1.0
  - 1.0
  - -1.0
  - 1.0
  offset: null
head:
  port: /dev/ttyUSB0
  motor_id: 0
  hold_motor_rad: 2.497
